name: codacy-coverage-reporter-action

on:
  workflow_dispatch:
    inputs:
      action-tag:
        description: "Tag for the action"
        required: true
        default: "main"

permissions:
  contents: read

jobs:
  codacy-coverage-reporter-action-main:
    name: Codacy Coverage Reporter (main)
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Upload Coverage to Codacy
        continue-on-error: true
        uses: step-security/codacy-coverage-reporter-action@main
        with:
          project-token: "49CVZHbGyYRvAKw08VIQ"
          coverage-reports: "testdata/code-coverage-report-action/coverage.xml"
