name: github-app-auth-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  github-app-auth-action-main:
    name: GitHub App Auth
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v6

      - name: Get GitHub App Token
        id: auth
        uses: step-security/github-app-auth-action@release
        with:
          creds: ${{ secrets.GH_APP_CREDS }}

      - name: Verify token
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
        run: |
          gh api /installation/repositories \
            --jq '.repositories[].full_name'