name: "setup-zig"

on:
  workflow_dispatch:
    inputs:
      action-tag:
        description: "Tag for the setup-zig-action"
        required: true
        default: "main"

jobs:
  setup-zig-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig Compiler
        id: setup-zig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: step-security/dynamic-uses@v1
        with:
          uses: step-security/setup-zig@${{ github.event.inputs.action-tag }}
          with: >
            {
              "version": "latest",
              "use-cache": "true"
            }
      - name: Build and Test Zig Project
        run: |
          echo "Zig setup action completed."
          echo "Version: latest"
          echo "Action Tag Used: ${{ github.event.inputs.action-tag }}"
          zig build
          zig build test