name: mongodb github action

on: 
    workflow_dispatch:
      inputs:
        action-tag:
          description: 'Tag for the action'
          required: true
          default: 'main'

jobs:
  mongodb-action:
    name: Start MongoDB Server v${{ matrix.mongodb-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0', '4.2', '4.4', '5.0', '6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server
        uses: step-security/dynamic-uses@v1
        with:
          uses: step-security/mongodb-github-action@${{ github.event.inputs.action-tag }}
          with: >
            {
                "mongodb-version": ${{ matrix.mongodb-version }}
            }