name: Test GitHubToken Permissions
	on:
	  push:
	    branches:
	      - main
	jobs:
	  test-permissions:
	    runs-on: ubuntu-latest
	    # Minimal permissions for GITHUB_TOKEN
	    permissions:
	      contents: read
	      issues: none
	      pull-requests: none
	      actions: none
	      checks: read
	      deployments: none
	      statuses: read
	      packages: none
	      repository-projects: none
	      discussions: none
	      security-events: none
	    steps:
	      - name: Checkout code
	        uses: actions/checkout@v3
	      - name: Dummy Step
	        run: echo "Testing minimal token permissions"